import type {
  Organization,
  Profile,
  Proposal,
  ProposalItem,
  Request,
  Comment,
  Deliverable,
  ClientOnboarding,
  Plan,
  PlanItem,
  PlanFeedback,
  PerformanceReport,
  Order,
  OrderItem,
  Subscription,
  Payment,
} from "../database.types";

export const TEST_STAFF_ID = "staff-priya";

export const ORG_AURORA_ID = "org-aurora";
export const ORG_NORTHWIND_ID = "org-northwind";

export const mockOrganizations: Organization[] = [
  { id: ORG_AURORA_ID, name: "Aurora Skincare", stripe_customer_id: null, status: "active", created_at: "2026-08-01T00:00:00Z" },
  { id: ORG_NORTHWIND_ID, name: "Northwind Coffee Co.", stripe_customer_id: null, status: "active", created_at: "2026-08-10T00:00:00Z" },
];

export const mockProfiles: Profile[] = [
  { id: "staff-morgan", org_id: null, role: "internal", full_name: "Morgan Lee", is_active: true, created_at: "2026-07-01T00:00:00Z" },
  { id: TEST_STAFF_ID, org_id: null, role: "admin", full_name: "Priya Nandan", is_active: true, created_at: "2026-06-01T00:00:00Z" },
];

export const mockProposals: Proposal[] = [
  {
    id: "prop-aurora-1",
    org_id: ORG_AURORA_ID,
    created_by: TEST_STAFF_ID,
    status: "pending",
    total_price: 738,
    created_at: "2026-09-10T00:00:00Z",
    responded_at: null,
  },
  {
    id: "prop-northwind-1",
    org_id: ORG_NORTHWIND_ID,
    created_by: TEST_STAFF_ID,
    status: "approved",
    total_price: 1278,
    created_at: "2026-08-15T00:00:00Z",
    responded_at: "2026-08-16T00:00:00Z",
  },
];

export const mockProposalItems: ProposalItem[] = [
  { id: "item-aurora-1", proposal_id: "prop-aurora-1", service_id: "social-media-posts", tier_label: "30 Posts", price: 279 },
  { id: "item-aurora-2", proposal_id: "prop-aurora-1", service_id: "short-form-videos", tier_label: "20 Videos", price: 459 },
  { id: "item-northwind-1", proposal_id: "prop-northwind-1", service_id: "social-media-posts", tier_label: "20 Posts", price: 179 },
  { id: "item-northwind-2", proposal_id: "prop-northwind-1", service_id: "ugc-content", tier_label: "6 Videos", price: 1099 },
];

export const mockRequests: Request[] = [
  {
    id: "req-1",
    org_id: ORG_NORTHWIND_ID,
    proposal_item_id: "item-northwind-1",
    plan_item_id: null,
    title: "September Instagram carousel batch",
    description: "First batch of branded carousel posts for Instagram + LinkedIn.",
    service_type: "social-media-posts",
    stage: "requested",
    assigned_to: null,
    created_by: TEST_STAFF_ID,
    due_date: "2026-10-06",
    format: "carousel",
    platforms: ["instagram", "linkedin"],
    publish_at: null,
    order_item_id: "oi-northwind-posts",
    units: 3,
    created_at: "2026-09-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "req-2",
    org_id: ORG_NORTHWIND_ID,
    proposal_item_id: "item-northwind-2",
    plan_item_id: null,
    title: "Founder story UGC video",
    description: "A founder-led UGC video introducing the new cold brew line.",
    service_type: "ugc-content",
    stage: "in_progress",
    assigned_to: "staff-morgan",
    created_by: TEST_STAFF_ID,
    due_date: "2026-10-02",
    format: "ugc_video",
    platforms: ["tiktok", "instagram"],
    publish_at: "2026-10-08T16:00:00Z",
    order_item_id: null,
    units: 1,
    created_at: "2026-08-20T00:00:00Z",
    updated_at: "2026-09-05T00:00:00Z",
  },
  {
    id: "req-3",
    org_id: ORG_NORTHWIND_ID,
    proposal_item_id: "item-northwind-2",
    plan_item_id: null,
    title: "Cold brew launch UGC set",
    description: "Three creator-led videos for the cold brew launch.",
    service_type: "ugc-content",
    stage: "review",
    assigned_to: "staff-morgan",
    created_by: TEST_STAFF_ID,
    due_date: "2026-09-29",
    format: "reel",
    platforms: ["instagram", "tiktok"],
    publish_at: "2026-10-01T14:30:00Z",
    order_item_id: null,
    units: 1,
    created_at: "2026-08-22T00:00:00Z",
    updated_at: "2026-09-12T00:00:00Z",
  },
  {
    id: "req-4",
    org_id: ORG_NORTHWIND_ID,
    proposal_item_id: "item-northwind-1",
    plan_item_id: null,
    title: "September content calendar",
    description: "Full content calendar and copy for the month.",
    service_type: "social-media-posts",
    stage: "delivered",
    assigned_to: "staff-morgan",
    created_by: TEST_STAFF_ID,
    due_date: "2026-09-10",
    format: "graphic",
    platforms: ["linkedin"],
    publish_at: "2026-09-15T13:00:00Z",
    order_item_id: "oi-northwind-posts",
    units: 4,
    created_at: "2026-08-25T00:00:00Z",
    updated_at: "2026-09-09T00:00:00Z",
  },
];

// This billing period (Aug 30 – Sep 30) against the order ledger below.
export const mockLedgerRequests: Request[] = [
  {
    id: "req-5",
    org_id: ORG_NORTHWIND_ID,
    proposal_item_id: null,
    plan_item_id: null,
    title: "Cold brew launch teaser posts",
    description: "Four teaser graphics counting down to the cold brew drop. Keep the can front and centre.",
    service_type: "social-media-posts",
    stage: "delivered",
    assigned_to: "staff-morgan",
    created_by: "client-northwind",
    due_date: "2026-09-12",
    format: "graphic",
    platforms: ["instagram"],
    publish_at: "2026-09-14T15:00:00Z",
    order_item_id: "oi-northwind-posts",
    units: 4,
    created_at: "2026-09-03T00:00:00Z",
    updated_at: "2026-09-11T00:00:00Z",
  },
  {
    id: "req-6",
    org_id: ORG_NORTHWIND_ID,
    proposal_item_id: null,
    plan_item_id: null,
    title: "Barista tips carousel",
    description: "Two carousels with at-home cold brew tips from our head barista.",
    service_type: "social-media-posts",
    stage: "in_progress",
    assigned_to: "staff-morgan",
    created_by: "client-northwind",
    due_date: "2026-10-03",
    format: "carousel",
    platforms: ["instagram", "linkedin"],
    publish_at: null,
    order_item_id: "oi-northwind-posts",
    units: 2,
    created_at: "2026-09-18T00:00:00Z",
    updated_at: "2026-09-20T00:00:00Z",
  },
  {
    id: "req-7",
    org_id: ORG_NORTHWIND_ID,
    proposal_item_id: null,
    plan_item_id: null,
    title: "Instagram + TikTok profile audit",
    description: "Audit both profiles before the launch push. Bio, highlights, pinned posts, link in bio.",
    service_type: "platform-audit",
    stage: "in_progress",
    assigned_to: TEST_STAFF_ID,
    created_by: "client-northwind",
    due_date: "2026-10-01",
    format: "other",
    platforms: ["instagram", "tiktok"],
    publish_at: null,
    order_item_id: "oi-northwind-audit",
    units: 1,
    created_at: "2026-09-01T00:00:00Z",
    updated_at: "2026-09-02T00:00:00Z",
  },
];
mockRequests.push(...mockLedgerRequests);

export const mockComments: Comment[] = [
  {
    id: "comment-1",
    request_id: "req-3",
    author_id: "staff-morgan",
    body: "First cut uploaded — let us know if the pacing works before we lock the final export.",
    visibility: "client",
    created_at: "2026-09-12T14:00:00Z",
  },
  {
    id: "comment-2",
    request_id: "req-3",
    author_id: TEST_STAFF_ID,
    body: "Client mentioned on the call they want a slightly warmer color grade — flagging before final.",
    visibility: "internal",
    created_at: "2026-09-12T15:30:00Z",
  },
];

// Northwind is the "approved & in progress" fixture client — gets the full
// Phase 2/3 story (onboarding reviewed, plan approved) so test mode actually
// exercises those pages. Aurora stays on the legacy pending-proposal path
// (no onboarding/plan rows) to keep that fallback branch covered too.
export const mockClientOnboarding: ClientOnboarding[] = [
  {
    id: "onboarding-northwind",
    org_id: ORG_NORTHWIND_ID,
    status: "reviewed",
    answers: {
      business_name: "Northwind Coffee Co.",
      business_description: "Specialty cold brew roaster shipping direct-to-consumer.",
      target_audience: "Coffee enthusiasts, 25-40, urban",
      brand_voice: "Warm, a little irreverent, never corporate",
      platforms: ["instagram", "tiktok"],
      existing_handles: "@northwindcoffee",
      goals: "Grow Instagram to 25k, launch a TikTok presence",
      inspiration: "Partake Foods, Blank Street Coffee",
      content_guidelines: "No stock photography, always feature real product",
    },
    submitted_at: "2026-08-12T00:00:00Z",
    reviewed_at: "2026-08-13T00:00:00Z",
    reviewed_by: "staff-morgan",
    created_at: "2026-08-10T00:00:00Z",
  },
];

export const mockPlans: Plan[] = [
  {
    id: "plan-northwind-1",
    org_id: ORG_NORTHWIND_ID,
    created_by: TEST_STAFF_ID,
    status: "approved",
    version: 1,
    supersedes_plan_id: null,
    total_price: 10174,
    sent_at: "2026-08-14T00:00:00Z",
    viewed_at: "2026-08-14T12:00:00Z",
    responded_at: "2026-08-16T00:00:00Z",
    created_at: "2026-08-13T00:00:00Z",
  },
];

export const mockPlanItems: PlanItem[] = [
  {
    id: "plan-item-northwind-1",
    plan_id: "plan-northwind-1",
    service_id: "social-media-posts",
    deliverable_label: "Instagram carousel batch",
    quantity: 20,
    frequency: "monthly",
    platform: "instagram",
    price: 179,
    notes: null,
  },
  {
    id: "plan-item-northwind-2",
    plan_id: "plan-northwind-1",
    service_id: "ugc-content",
    deliverable_label: "Founder-led UGC videos",
    quantity: 6,
    frequency: "monthly",
    platform: "tiktok",
    price: 1099,
    notes: "Cold brew launch focus for the first batch.",
  },
];

export const mockPlanFeedback: PlanFeedback[] = [
  {
    id: "plan-feedback-1",
    plan_id: "plan-northwind-1",
    author_id: "client-northwind",
    body: "Can we swap one of the Instagram carousels for a Reel each month? Reels are outperforming static posts for us right now.",
    created_at: "2026-08-15T00:00:00Z",
  },
  {
    id: "plan-feedback-2",
    plan_id: "plan-northwind-1",
    author_id: TEST_STAFF_ID,
    body: "Good call — we'll rotate one carousel slot to a Reel each month starting this batch.",
    created_at: "2026-08-15T10:00:00Z",
  },
];

export const mockDeliverables: Deliverable[] = [
  {
    id: "deliverable-1",
    request_id: "req-4",
    file_path: `${ORG_NORTHWIND_ID}/req-4/september-content-calendar.pdf`,
    uploaded_by: "staff-morgan",
    created_at: "2026-09-09T00:00:00Z",
  },
];

// Sample results so the Results tab has something to chart in test mode.
export const mockPerformanceReports: PerformanceReport[] = [
  {
    id: "report-1",
    org_id: ORG_NORTHWIND_ID,
    period_month: "2026-07-01",
    platform: "instagram",
    followers: 1840,
    reach: 9200,
    engagement_rate: 3.9,
    posts_published: 14,
    notes: null,
    created_by: TEST_STAFF_ID,
    created_at: "2026-07-01T00:00:00Z",
    updated_at: "2026-07-01T00:00:00Z",
  },
  {
    id: "report-2",
    org_id: ORG_NORTHWIND_ID,
    period_month: "2026-07-01",
    platform: "tiktok",
    followers: 920,
    reach: 15400,
    engagement_rate: 6.1,
    posts_published: 10,
    notes: null,
    created_by: TEST_STAFF_ID,
    created_at: "2026-07-01T00:00:00Z",
    updated_at: "2026-07-01T00:00:00Z",
  },
  {
    id: "report-3",
    org_id: ORG_NORTHWIND_ID,
    period_month: "2026-08-01",
    platform: "instagram",
    followers: 2210,
    reach: 11800,
    engagement_rate: 4.3,
    posts_published: 16,
    notes: null,
    created_by: TEST_STAFF_ID,
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "report-4",
    org_id: ORG_NORTHWIND_ID,
    period_month: "2026-08-01",
    platform: "tiktok",
    followers: 1510,
    reach: 24100,
    engagement_rate: 6.8,
    posts_published: 12,
    notes: null,
    created_by: TEST_STAFF_ID,
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "report-5",
    org_id: ORG_NORTHWIND_ID,
    period_month: "2026-09-01",
    platform: "instagram",
    followers: 2690,
    reach: 14100,
    engagement_rate: 4.6,
    posts_published: 16,
    notes: null,
    created_by: TEST_STAFF_ID,
    created_at: "2026-09-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "report-6",
    org_id: ORG_NORTHWIND_ID,
    period_month: "2026-09-01",
    platform: "tiktok",
    followers: 2380,
    reach: 31900,
    engagement_rate: 7.2,
    posts_published: 14,
    notes: null,
    created_by: TEST_STAFF_ID,
    created_at: "2026-09-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
];

// Northwind's checkout: a monthly 10-post line plus a one-time audit add-on.
export const mockOrders: Order[] = [
  {
    id: "order-northwind-1",
    org_id: ORG_NORTHWIND_ID,
    created_by: "client-northwind",
    status: "paid",
    currency: "usd",
    amount_subtotal: 17800,
    amount_total: 17800,
    stripe_checkout_session_id: null,
    stripe_customer_id: null,
    stripe_subscription_id: "sub_northwind",
    created_at: "2026-07-30T12:00:00Z",
    paid_at: "2026-07-30T12:00:00Z",
  },
];

export const mockOrderItems: OrderItem[] = [
  {
    id: "oi-northwind-posts",
    order_id: "order-northwind-1",
    service_id: "social-media-posts",
    tier_label: "10 Posts",
    item_type: "service",
    billing_interval: "month",
    unit_amount: 7900,
    quantity: 1,
    units: 10,
  },
  {
    id: "oi-northwind-audit",
    order_id: "order-northwind-1",
    service_id: "platform-audit",
    tier_label: "One-time",
    item_type: "addon",
    billing_interval: "one_time",
    unit_amount: 9900,
    quantity: 1,
    units: 1,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: "subscription-northwind",
    org_id: ORG_NORTHWIND_ID,
    order_id: "order-northwind-1",
    stripe_subscription_id: "sub_northwind",
    status: "active",
    current_period_end: "2026-09-30T12:00:00Z",
    cancel_at_period_end: false,
    created_at: "2026-07-30T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z",
  },
];

export const mockPayments: Payment[] = [
  {
    id: "payment-northwind-1",
    org_id: ORG_NORTHWIND_ID,
    order_id: "order-northwind-1",
    subscription_id: null,
    stripe_payment_intent_id: null,
    stripe_invoice_id: null,
    status: "succeeded",
    amount: 17800,
    currency: "usd",
    created_at: "2026-07-30T12:00:00Z",
  },
  {
    id: "payment-northwind-2",
    org_id: ORG_NORTHWIND_ID,
    order_id: null,
    subscription_id: "subscription-northwind",
    stripe_payment_intent_id: null,
    stripe_invoice_id: null,
    status: "succeeded",
    amount: 7900,
    currency: "usd",
    created_at: "2026-08-30T12:00:00Z",
  },
];
